version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  kube-orb: circleci/kubernetes@dev:alpha

executors:
  ci-base:
    docker:
      - image: cimg/base:stable
        environment:
          # For testing the install-kubeconfig command
          KUBECONFIG: dGVzdA==

  machine:
    machine: true

  minikube:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      CHANGE_MINIKUBE_NONE_USER=true

  macos:
    macos:
      xcode: "10.1.0"

commands:
  start-minikube:
    steps:
      - run:
          name: Start minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
              && chmod +x minikube
            sudo cp minikube /usr/local/bin && rm minikube
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048
  integration-tests:
    steps:
      - checkout
      - kube-orb/install
      - run:
          name: Test kops
          command: kops version
      - run:
          name: Test kubectl
          command: kubectl
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG
      - run:
          name: Test kubeconfig output
          command: |
            [[ -f $HOME/.kube/config && ! -z $HOME/.kube/config && $(<$HOME/.kube/config) == "test" ]]
  integration-tests-specific-version:
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
          kops-version: 1.12.2
      - run:
          name: Test kops version
          command: kops version | grep "1.12.2"
      - run:
          name: Test kubectl version
          command: |
            set +e
            # ignore connection refused error
            KUBECTL_VERSION=$(kubectl version)
            set -e
            echo $KUBECTL_VERSION | grep "v1.15.2"

jobs:
  integration-test-docker:
    executor: ci-base
    steps:
      - integration-tests

  integration-test-machine:
    executor: machine
    steps:
      - integration-tests-specific-version

  integration-test-macos:
    executor: macos
    steps:
      - integration-tests

  integration-test-kubectl:
    executor: minikube
    steps:
      - checkout
      - kube-orb/install-kubectl
      - start-minikube
      - kube-orb/create-or-update-resource:
          resource-file-path: "tests/nginx-deployment/deployment.yaml"
          resource-name: "deployment/nginx-deployment"
          get-rollout-status: true
          show-kubectl-command: true
      - kube-orb/update-container-image:
          resource-name: "deployment/nginx-deployment"
          container-image-updates: "nginx=nginx:1.9.1 redis=redis:5-buster"
          record: true
      - kube-orb/get-rollout-status:
          resource-name: "deployment/nginx-deployment"
          watch-rollout-status: true
      - kube-orb/delete-resource:
          resource-types: "deployments"
          resource-names: "nginx-deployment"
          now: true
          wait: true
# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [integration-test-docker-master, integration-test-machine-master, integration-test-macos-master, integration-test-kubectl-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/kubernetes
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 1b:26:fb:58:c5:a1:95:ef:13:93:11:4e:dd:42:41:2d
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 1b:26:fb:58:c5:a1:95:ef:13:93:11:4e:dd:42:41:2d
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # non-master branch tests
      - integration-test-docker:
          name: integration-test-docker-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - integration-test-machine:
          name: integration-test-machine-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - integration-test-macos:
          name: integration-test-macos-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - integration-test-kubectl:
          name: integration-test-kubectl-dev
          context: orb-publishing
          filters: *integration-dev_filters

      # master-branch
      - integration-test-docker:
          name: integration-test-docker-master
          context: orb-publishing
          filters: *integration-master_filters

      - integration-test-machine:
          name: integration-test-machine-master
          context: orb-publishing
          filters: *integration-master_filters

      - integration-test-macos:
          name: integration-test-macos-master
          context: orb-publishing
          filters: *integration-master_filters

      - integration-test-kubectl:
          name: integration-test-kubectl-master
          context: orb-publishing
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/kubernetes
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/kubernetes
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/kubernetes
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
