description: |
  Install kubeconfig file with the contents taken from the value of an
  environment variable, which should be base64-encoded.

parameters:
  kubeconfig:
    type: env_var_name
    description: Environment variable name containing base64-encoded kubeconfig data
    default: KUBECONFIG_DATA

# steps:
#   - run:
#       name: Install kubeconfig
#       environment:
#         PARAM_KUBECONFIG: <<parameters.kubeconfig>>
#       command: <<include(scripts/install-kubeconfig.sh)>>
steps:
  - run:
      name: Install kubeconfig
      command: |
        if [ -n "${<<parameters.kubeconfig>>}" ]; then
          mkdir -p $HOME/.kube
          echo -n "${<<parameters.kubeconfig>>}" | base64 --decode > $HOME/.kube/config
        fi
