description: |
  Install kubeconfig file with the contents taken from the value of an
  environment variable, which should be base64-encoded.

parameters:
  kubeconfig:
    type: env_var_name
    description: Environment variable containing base64-encoded kubeconfig data
    default: KUBECONFIG_DATA

steps:
  - run:
      name: Install kubeconfig
      environment:
        K8_ENV_KUBECONFIG: <<parameters.kubeconfig>>
      command: <<include(scripts/install_kubeconfig.sh)>>
