description: |
  Update kubernetes resource.

usage:
  version: 2.1

  orbs:
    kubernetes: circleci/kubernetes@x.y.z

  jobs:
    update:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - kubernetes/install_kubectl
        - kubernetes/update_container_image:
            resource_name: "deployment/nginx-deployment"
            container_image_updates: "nginx=nginx:1.9.1"
            get_rollout_status: true
