description: |
  Deploying kubernetes resources.

usage:
  version: 2.1

  orbs:
    kube-orb: circleci/kubernetes@x.y.z

  jobs:
    create-update:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - kube-orb/install-kubectl
        - kube-orb/create-or-update-resource:
            resource-file-path: "tests/nginx-deployment/deployment.yaml"
            resource-name: "deployment/nginx-deployment"
            get-rollout-status: true
            show-kubectl-command: true
