description: |
  Update kubernetes resource.

usage:
  version: 2.1

  orbs:
    kubernetes: circleci/kubernetes@x.y.z

  jobs:
    update:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - kubernetes/install-kubectl
        - kubernetes/update-container-image:
            resource-name: "deployment/nginx-deployment"
            container-image-updates: "nginx=nginx:1.9.1"
            get-rollout-status: true
