description: |
  Install kubeconfig

usage:
  version: 2.1

  orbs:
    kubernetes: circleci/kubernetes@1.0.0

  jobs:
    build:
      macos:
        xcode: "9.0"
      steps:
        - checkout
        - kubernetes/install-kubeconfig:
            kubeconfig: KUBECONFIG_DATA
